---
# tasks file for myloadblancer

- name: Installing Haproxy
  package:
          name: haproxy
          state: present

- name: Copying Haproxy.cfg file 
  template:
          src: haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg
  notify:
  - restart_haproxy

- name: starting Haproxy Services
  service: 
        name: haproxy
        state: started  

