---
# tasks file for myapache

- name: Installing Httpd
  package:
          name: httpd
          state: present

- name: Installing PHP
  package:
          name: php
          state: present

- name: copying  web page 
  template:
          src: index.php
          dest: /var/www/html/index.php

- name: Starting Httpd Service 
  service:
          name: httpd
          state: started
